workflows:
  ios-workflow:
    name: iOS Build
    scripts:
      - npm install
      - npm run build
      - npx cap sync ios
      - xcodebuild -workspace ios/App/App.xcworkspace -scheme App -configuration Release
    artifacts:
      - ios/App/build/Release-iphoneos/*.ipa
