workflows:
  ios-emergency-build:
    name: Emergency iOS Build
    environment:
      xcode: latest
    scripts:
      - npm install
      - npm run build
      - npx cap add ios --force
      - npx cap sync ios
      - xcodebuild build -workspace ios/App/App.xcworkspace -scheme App -configuration Release
    artifacts:
      - ios/App/build/Release-iphoneos/*.ipa