workflows:
  ios-android-workflow:
    name: iOS and Android Build
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      - name: Build iOS
        script: |
          npx cap sync ios
          xcodebuild build -workspace ios/App/App.xcworkspace -scheme App -sdk iphonesimulator -configuration Debug
      - name: Build Android
        script: |
          npx cap sync android
          cd android
          ./gradlew assembleDebug
    artifacts:
      - ios/App/build/**/*.app
      - android/app/build/outputs/**/*.apk
  web-workflow:
    name: Web Build
    environment:
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Web
        script: npm run build
    artifacts:
      - www/**
