# codemagic.yaml
workflows:
  ios-emergency-build:
    name: Guaranteed iOS Build
    environment:
      xcode: latest
    scripts:
      - npm install -g @capacitor/cli cordova-res
      - npm install
      - npm run build --if-present  # Bypass missing build script
      - npx cap add ios --force
      - npx cap sync ios
      - cd ios && pod install
      - xcodebuild build -workspace App/App.xcworkspace -scheme App -configuration Release
    artifacts:
      - ios/App/build/Release-iphoneos/App.ipa
